
type IndicatorValueNCUWithToolTip {
  value: String!
  value_ncu: String !
  toolTip: ToolTip!
}

type OverviewTabRegional {
  # WHAT PERCENTAGE OF PEOPLE IN WAKISO LIVE BELOW THE NATIONAL POVERTY LINE? 
  # can be no data or '12%'
  poorestPeople: IndicatorValueWithToolTip!
  # WHAT RESOURCES ARE AVAILABLE TO LOCAL GOVERNMENTS IN WAKISO? eg 3.6m or 2.7bn
  # this is a total of local, donor and central government resources
  regionalResources: IndicatorValueNCUWithToolTip!
  # IndicatorDataColored is defined in country profile types
  # has local government, donor and central government
  regionalResourcesBreakdown: [IndicatorDataWithToolTip]!
  # HOW MUCH DOES THE LOCAL GOVERNMENT SPEND PER PERSON?
  localGovernmentSpendPerPerson: IndicatorValueWithToolTip!
}

type PovertyTabKe {
  poorestPeople: IndicatorValueWithToolTip!
  #WHAT IS THE AVERAGE LIFE EXPECTANCY? 
  meanExpenditure: IndicatorValueWithToolTip!
  #WHAT IS THE STANDARD OF LIVING SCORE? 
  povertyGap: IndicatorValueWithToolTip!
}
type PovertyTabUg {
  poorestPeople: IndicatorValueWithToolTip!
  #WHAT IS THE AVERAGE LIFE EXPECTANCY? 
  lifeExpectancy: IndicatorValueWithToolTip!
  #WHAT IS THE STANDARD OF LIVING SCORE? 
  stdOfLiving: IndicatorValueWithToolTip!
}

type PopulationTabRegionalKe {
  #The total population of a given district and the population density in per sq km
  totalPopulation: IndicatorValueWithToolTip!
  populationDensity: IndicatorValueWithToolTip!
  populationBirthRate: IndicatorValueWithToolTip!
}

type PopulationTabRegionalUg {
  #The total population of a given district and the population density in per sq km
  totalPopulation: IndicatorValueWithToolTip!
  populationDensity: IndicatorValueWithToolTip!
   # Urban vs Rural population level
  populationDistribution: PopulationDistributionWithToolTip!
  averageDependencyRatio: IndicatorValueWithToolTip!
  allAverageDependencyRatio: IndicatorValueWithToolTip!
}

type EducationTabRegionalUg {
  #WHAT IS THE PUPIL–TEACHER RATIO IN PRIMARY EDUCATION?...in government schools  and...in all schools 
  pupilTeacherRatioGovtSchl: IndicatorValueWithToolTip!
  pupilTeacherRatioOtherSchl: IndicatorValueWithToolTip!
  #WHAT PERCENTAGE OF STUDENTS PASS THE PRIMARY LEAVING EXAM? 
  studentsPassRate: IndicatorValueWithToolTip!
  studentsPassDistrictRank: IndicatorValueWithToolTip!
  #HOW MUCH PRIMARY EDUCATION FUNDING IS THERE? 
  primaryEducationfunding:  IndicatorValueNCUWithToolTip!
}

type EducationTabRegionalKe {
  #WHAT IS THE PUPIL–TEACHER RATIO IN PRIMARY EDUCATION?...in government schools  and...in all schools 
  primaryPupilTeacherRatioAllSchl: IndicatorValueWithToolTip!
  primaryTeacherRatioPublicSchl: IndicatorValueWithToolTip !
  primaryTeacherRatioPrivateSchl: IndicatorValueWithToolTip!
}

type HealthTabRegionalUg {
  #WHAT IS THE DISTRICT LEAGUE HEALTH PERFORMANCE SCORE?
  districtPerformance: IndicatorValueWithToolTip!
  #WHAT PERCENTAGE OF TUBERCULOSIS CASES HAVE BEEN SUCCESSFULLY TREATED? 
  treatmeantOfTb: IndicatorValueWithToolTip!
  districtHealthRank: IndicatorValueWithToolTip!
  #HOW MUCH LOCAL GOVERNMENT HEALTHCARE FUNDING IS THERE? 
  healthCareFunding: IndicatorValueNCUWithToolTip!
}

type HealthTabRegionalKe {
  birthAttendanceSkilled: IndicatorValueWithToolTip! 
  contraceptiveUse: IndicatorValueWithToolTip !
  healthCareFunding: IndicatorValueNCUWithToolTip!
}


type LocalGovernmentFinance {
  startYear: Int!
  currencyUSD: String!
  currencyCode: String!
  # come from finance file
  revenueAndGrants: [Domestic]!
  expenditure: [Domestic]!
}

# union PovertyTabRegional = PovertyTabUg | PovertyTabKe
# union PopulationTabRegional = PopulationTabRegionalUg | PopulationTabRegionalKe
# union EducationTabRegional = EducationTabRegionalUg | EducationTabRegionalKe
# union HealthTabRegional = HealthTabRegionalKe | HealthTabRegionalUg

type Query {  
  # id is district slug
  overviewTabRegional(id: String!, country: String!):OverviewTabRegional
  # povertyTabRegional(id: String!, country: String!): PovertyTabRegional
  # populationTabRegional(id: String!, country: String!):PopulationTabRegional
  # educationTabRegional(id: String!, country: String!):  EducationTabRegional
  # healthTabRegional(id: String!, country: String!): HealthTabRegional
  # localGovernmentFinance(id: String!, country: String!): LocalGovernmentFinance
}
